const data = [
  {
    id: 1,
    img: "../img-products/arco-azul-amarelo.jpg",
    name: "Arco canarinho",
    value: 225,
    addCart: "Adicionar ao carrinho",
    promotion: "Não",
    category: "Arco",
  },
  {
    id: 2,
    img: "../img-products/arco-verde.jpg",
    name: "Arco verde",
    value: 15,
    addCart: "Adicionar ao carrinho",
    promotion: "Sim",
    category: "Arco",
  },
  {
    id: 3,
    img: "../img-products/laco-branco.jpg",
    name: "Lacinho branquinho",
    value: 52,
    addCart: "Adicionar ao carrinho",
    promotion: "Não",
    category: "Laço",
  },
  {
    id: 4,
    img: "../img-products/laco-rosa.jpg",
    name: "Lacinho azul",
    value: 20,
    addCart: "Adicionar ao carrinho",
    promotion: "Sim",
    category: "Laço",
  },
  {
    id: 5,
    img: "../img-products/laco-verde-barnco.jpg",
    name: "Laço canarinho",
    value: 125,
    addCart: "Adicionar ao carrinho",
    promotion: "Não",
    category: "Laço",
  },
];
